### ISSUE TITLE
Pop up thông báo của chức năng sản phẩm khi tạo thành công hay thất bại đều trả về thất bại

### ISSUE THREAD

**Issue by DarkW1llow** [DarkW1llow/SE04-Nhom20.4-Frontend-Adminv2#2]
Lý do - Là do GraphQL Server không hỗ trợ trả về status Code khi gửi HTTP Request

**Comment by macvanhieuhus** [comment]
Sẽ fix cứng là trả về thành công hết. Trường hợp thất bại thì sẽ không hiện ra pop up thông báo
